#include "include/guiaddons.hpp"

//#include "addons/imguibindings/imguibindings.h"
//#include "addons/imguilistview/imguilistview.h"
//#include "addons/imguifilesystem/imguifilesystem.h"
//#include "addons/imguitoolbar/imguitoolbar.h"
//#include "addons/imguipanelmanager/imguipanelmanager.h"
//#include "addons/imguivariouscontrols/imguivariouscontrols.h"
//#include "addons/imguistyleserializer/imguistyleserializer.h"
#include "addons/imguidatechooser/imguidatechooser.h"
//#include "addons/imguicodeeditor/imguicodeeditor.h"
//#include "addons/imguinodegrapheditor/imguinodegrapheditor.h"
//#include "addons/imguidock/imguidock.h"

ImTextureID myImageTextureId2 = 0;
void AddonsDatePicker::DisplayContents() {
    ImGui::BeginChild("Addons");
    {
		ImGui::Text("Choose a date:");
		ImGui::SameLine();
		static tm myDate = {};       // IMPORTANT: must be static! (plenty of compiler warnings here if we write: static tm myDate={0}; Is there any difference?)
		ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x * 0.5f);
		ImGui::PushItemWidth(35.0f * 5.0f);
		if (ImGui::DateChooser("Date Chooser##MyDateChooser", myDate, "%a, %d %b %Y")) {
			// A new date has been chosen
			//fprintf(stderr,"A new date has been chosen exacty now: \"%.2d-%.2d-%.4d\"\n",myDate.tm_mday,myDate.tm_mon+1,myDate.tm_year+1900);
		}
		ImGui::PopItemWidth();
		ImGui::Text("Chosen date: \"%.2d-%.2d-%.4d\"", myDate.tm_mday, myDate.tm_mon + 1, myDate.tm_year + 1900);
        ImGui::Spacing();
        ImGui::AlignTextToFramePadding();
        ImGui::Text("Choose another date:");
        ImGui::SameLine();
        static tm myDate2 = {};       // IMPORTANT: must be static! (plenty of compiler warnings here if we write: static tm myDate={0}; Is there any difference?)
        ImGui::PushItemWidth(35.0f * 10.0f);
        if (ImGui::DateChooser("##MyDateChooser2", myDate2, "%d/%m/%Y")) {
            // A new date has been chosen
            //fprintf(stderr,"A new date has been chosen exacty now: \"%.2d-%.2d-%.4d\"\n",myDate2.tm_mday,myDate2.tm_mon+1,myDate2.tm_year+1900);
        }
        ImGui::PopItemWidth();
        ImGui::Text("Chosen date2: \"%.2d-%.2d-%.4d\"", myDate2.tm_mday, myDate2.tm_mon + 1, myDate2.tm_year + 1900);

        
    }
    ImGui::EndChild();
}

ImVector<const char*> icons;
static int refresh = 1;

static ImGuiTableFlags iconTableFlags = ImGuiTableFlags_RowBg |
ImGuiTableFlags_BordersV |
ImGuiTableFlags_Resizable |
ImGuiTableFlags_ContextMenuInBody |
ImGuiTableFlags_BordersOuter |
//ImGuiTableFlags_Reorderable |
ImGuiTableFlags_SizingStretchSame |
//ImGuiTableFlags_Sortable |
ImGuiTableFlags_ScrollY |
ImGuiTableFlags_NoHostExtendY;

void FillIcons(ImVector<const char*>& m_icons) {
    m_icons.push_back("\xef\x99\x81 Ad");
    m_icons.push_back("\xef\x8a\xb9 Address Book");
    m_icons.push_back("\xef\x8a\xbb Address Card");
    m_icons.push_back("\xef\x81\x82 Adjust");
    m_icons.push_back("\xef\x97\x90 Air Freshener");
    m_icons.push_back("\xef\x80\xb7 Align Center");
    m_icons.push_back("\xef\x80\xb9 Align Justify");
    m_icons.push_back("\xef\x80\xb6 Align Left");
    m_icons.push_back("\xef\x80\xb8 Align Right");
    m_icons.push_back("\xef\x91\xa1 Allergies");
    m_icons.push_back("\xef\x83\xb9 Ambulance");
    m_icons.push_back("\xef\x8a\xa3 American Sign Language Interpreting");
    m_icons.push_back("\xef\x84\xbd Anchor");
    m_icons.push_back("\xef\x84\x83 Angle Double Down");
    m_icons.push_back("\xef\x84\x80 Angle Double Left");
    m_icons.push_back("\xef\x84\x81 Angle Double Right");
    m_icons.push_back("\xef\x84\x82 Angle Double Up");
    m_icons.push_back("\xef\x84\x87 Angle Down");
    m_icons.push_back("\xef\x84\x84 Angle Left");
    m_icons.push_back("\xef\x84\x85 Angle Right");
    m_icons.push_back("\xef\x84\x86 Angle Up");
    m_icons.push_back("\xef\x95\x96 Angry");
    m_icons.push_back("\xef\x99\x84 Ankh");
    m_icons.push_back("\xef\x97\x91 Apple Alt");
    m_icons.push_back("\xef\x86\x87 Archive");
    m_icons.push_back("\xef\x95\x97 Archway");
    m_icons.push_back("\xef\x8d\x98 Arrow Alt Circle Down");
    m_icons.push_back("\xef\x8d\x99 Arrow Alt Circle Left");
    m_icons.push_back("\xef\x8d\x9a Arrow Alt Circle Right");
    m_icons.push_back("\xef\x8d\x9b Arrow Alt Circle Up");
    m_icons.push_back("\xef\x82\xab Arrow Circle Down");
    m_icons.push_back("\xef\x82\xa8 Arrow Circle Left");
    m_icons.push_back("\xef\x82\xa9 Arrow Circle Right");
    m_icons.push_back("\xef\x82\xaa Arrow Circle Up");
    m_icons.push_back("\xef\x81\xa3 Arrow Down");
    m_icons.push_back("\xef\x81\xa0 Arrow Left");
    m_icons.push_back("\xef\x81\xa1 Arrow Right");
    m_icons.push_back("\xef\x81\xa2 Arrow Up");
    m_icons.push_back("\xef\x82\xb2 Arrows Alt");
    m_icons.push_back("\xef\x8c\xb7 Arrows Alt H");
    m_icons.push_back("\xef\x8c\xb8 Arrows Alt V");
    m_icons.push_back("\xef\x8a\xa2 Assistive Listening Systems");
    m_icons.push_back("\xef\x81\xa9 Asterisk");
    m_icons.push_back("\xef\x87\xba At");
    m_icons.push_back("\xef\x95\x98 Atlas");
    m_icons.push_back("\xef\x97\x92 Atom");
    m_icons.push_back("\xef\x8a\x9e Audio Description");
    m_icons.push_back("\xef\x95\x99 Award");
    m_icons.push_back("\xef\x9d\xbc Baby");
    m_icons.push_back("\xef\x9d\xbd Baby Carriage");
    m_icons.push_back("\xef\x95\x9a Backspace");
    m_icons.push_back("\xef\x81\x8a Backward");
    m_icons.push_back("\xef\x9f\xa5 Bacon");
    m_icons.push_back("\xee\x81\x99 Bacteria");
    m_icons.push_back("\xee\x81\x9a Bacterium");
    m_icons.push_back("\xef\x99\xa6 Bahai");
    m_icons.push_back("\xef\x89\x8e Balance Scale");
    m_icons.push_back("\xef\x94\x95 Balance Scale Left");
    m_icons.push_back("\xef\x94\x96 Balance Scale Right");
    m_icons.push_back("\xef\x81\x9e Ban");
    m_icons.push_back("\xef\x91\xa2 Band Aid");
    m_icons.push_back("\xef\x80\xaa Barcode");
    m_icons.push_back("\xef\x83\x89 Bars");
    m_icons.push_back("\xef\x90\xb3 Baseball Ball");
    m_icons.push_back("\xef\x90\xb4 Basketball Ball");
    m_icons.push_back("\xef\x8b\x8d Bath");
    m_icons.push_back("\xef\x89\x84 Battery Empty");
    m_icons.push_back("\xef\x89\x80 Battery Full");
    m_icons.push_back("\xef\x89\x82 Battery Half");
    m_icons.push_back("\xef\x89\x83 Battery Quarter");
    m_icons.push_back("\xef\x89\x81 Battery Three Quarters");
    m_icons.push_back("\xef\x88\xb6 Bed");
    m_icons.push_back("\xef\x83\xbc Beer");
    m_icons.push_back("\xef\x83\xb3 Bell");
    m_icons.push_back("\xef\x87\xb6 Bell Slash");
    m_icons.push_back("\xef\x95\x9b Bezier Curve");
    m_icons.push_back("\xef\x99\x87 Bible");
    m_icons.push_back("\xef\x88\x86 Bicycle");
    m_icons.push_back("\xef\xa1\x8a Biking");
    m_icons.push_back("\xef\x87\xa5 Binoculars");
    m_icons.push_back("\xef\x9e\x80 Biohazard");
    m_icons.push_back("\xef\x87\xbd Birthday Cake");
    m_icons.push_back("\xef\x94\x97 Blender");
    m_icons.push_back("\xef\x9a\xb6 Blender Phone");
    m_icons.push_back("\xef\x8a\x9d Blind");
    m_icons.push_back("\xef\x9e\x81 Blog");
    m_icons.push_back("\xef\x80\xb2 Bold");
    m_icons.push_back("\xef\x83\xa7 Bolt");
    m_icons.push_back("\xef\x87\xa2 Bomb");
    m_icons.push_back("\xef\x97\x97 Bone");
    m_icons.push_back("\xef\x95\x9c Bong");
    m_icons.push_back("\xef\x80\xad Book");
    m_icons.push_back("\xef\x9a\xb7 Book Dead");
    m_icons.push_back("\xef\x9f\xa6 Book Medical");
    m_icons.push_back("\xef\x94\x98 Book Open");
    m_icons.push_back("\xef\x97\x9a Book Reader");
    m_icons.push_back("\xef\x80\xae Bookmark");
    m_icons.push_back("\xef\xa1\x8c Border All");
    m_icons.push_back("\xef\xa1\x90 Border None");
    m_icons.push_back("\xef\xa1\x93 Border Style");
    m_icons.push_back("\xef\x90\xb6 Bowling Ball");
    m_icons.push_back("\xef\x91\xa6 Box");
    m_icons.push_back("\xef\x92\x9e Box Open");
    m_icons.push_back("\xee\x81\x9b Box Tissue");
    m_icons.push_back("\xef\x91\xa8 Boxes");
    m_icons.push_back("\xef\x8a\xa1 Braille");
    m_icons.push_back("\xef\x97\x9c Brain");
    m_icons.push_back("\xef\x9f\xac Bread Slice");
    m_icons.push_back("\xef\x82\xb1 Briefcase");
    m_icons.push_back("\xef\x91\xa9 Briefcase Medical");
    m_icons.push_back("\xef\x94\x99 Broadcast Tower");
    m_icons.push_back("\xef\x94\x9a Broom");
    m_icons.push_back("\xef\x95\x9d Brush");
    m_icons.push_back("\xef\x86\x88 Bug");
    m_icons.push_back("\xef\x86\xad Building");
    m_icons.push_back("\xef\x82\xa1 Bullhorn");
    m_icons.push_back("\xef\x85\x80 Bullseye");
    m_icons.push_back("\xef\x91\xaa Burn");
    m_icons.push_back("\xef\x88\x87 Bus");
    m_icons.push_back("\xef\x95\x9e Bus Alt");
    m_icons.push_back("\xef\x99\x8a Business Time");
    m_icons.push_back("\xef\x87\xac Calculator");
    m_icons.push_back("\xef\x84\xb3 Calendar");
    m_icons.push_back("\xef\x81\xb3 Calendar Alt");
    m_icons.push_back("\xef\x89\xb4 Calendar Check");
    m_icons.push_back("\xef\x9e\x83 Calendar Day");
    m_icons.push_back("\xef\x89\xb2 Calendar Minus");
    m_icons.push_back("\xef\x89\xb1 Calendar Plus");
    m_icons.push_back("\xef\x89\xb3 Calendar Times");
    m_icons.push_back("\xef\x9e\x84 Calendar Week");
    m_icons.push_back("\xef\x80\xb0 Camera");
    m_icons.push_back("\xef\x82\x83 Camera Retro");
    m_icons.push_back("\xef\x9a\xbb Campground");
    m_icons.push_back("\xef\x9e\x86 Candy Cane");
    m_icons.push_back("\xef\x95\x9f Cannabis");
    m_icons.push_back("\xef\x91\xab Capsules");
    m_icons.push_back("\xef\x86\xb9 Car");
    m_icons.push_back("\xef\x97\x9e Car Alt");
    m_icons.push_back("\xef\x97\x9f Car Battery");
    m_icons.push_back("\xef\x97\xa1 Car Crash");
    m_icons.push_back("\xef\x97\xa4 Car Side");
    m_icons.push_back("\xef\xa3\xbf Caravan");
    m_icons.push_back("\xef\x83\x97 Caret Down");
    m_icons.push_back("\xef\x83\x99 Caret Left");
    m_icons.push_back("\xef\x83\x9a Caret Right");
    m_icons.push_back("\xef\x85\x90 Caret Square Down");
    m_icons.push_back("\xef\x86\x91 Caret Square Left");
    m_icons.push_back("\xef\x85\x92 Caret Square Right");
    m_icons.push_back("\xef\x85\x91 Caret Square Up");
    m_icons.push_back("\xef\x83\x98 Caret Up");
    m_icons.push_back("\xef\x9e\x87 Carrot");
    m_icons.push_back("\xef\x88\x98 Cart Arrow Down");
    m_icons.push_back("\xef\x88\x97 Cart Plus");
    m_icons.push_back("\xef\x9e\x88 Cash Register");
    m_icons.push_back("\xef\x9a\xbe Cat");
    m_icons.push_back("\xef\x82\xa3 Certificate");
    m_icons.push_back("\xef\x9b\x80 Chair");
    m_icons.push_back("\xef\x94\x9b Chalkboard");
    m_icons.push_back("\xef\x94\x9c Chalkboard Teacher");
    m_icons.push_back("\xef\x97\xa7 Charging Station");
    m_icons.push_back("\xef\x87\xbe Chart Area");
    m_icons.push_back("\xef\x82\x80 Chart Bar");
    m_icons.push_back("\xef\x88\x81 Chart Line");
    m_icons.push_back("\xef\x88\x80 Chart Pie");
    m_icons.push_back("\xef\x80\x8c Check");
    m_icons.push_back("\xef\x81\x98 Check Circle");
    m_icons.push_back("\xef\x95\xa0 Check Double");
    m_icons.push_back("\xef\x85\x8a Check Square");
    m_icons.push_back("\xef\x9f\xaf Cheese");
    m_icons.push_back("\xef\x90\xb9 Chess");
    m_icons.push_back("\xef\x90\xba Chess Bishop");
    m_icons.push_back("\xef\x90\xbc Chess Board");
    m_icons.push_back("\xef\x90\xbf Chess King");
    m_icons.push_back("\xef\x91\x81 Chess Knight");
    m_icons.push_back("\xef\x91\x83 Chess Pawn");
    m_icons.push_back("\xef\x91\x85 Chess Queen");
    m_icons.push_back("\xef\x91\x87 Chess Rook");
    m_icons.push_back("\xef\x84\xba Chevron Circle Down");
    m_icons.push_back("\xef\x84\xb7 Chevron Circle Left");
    m_icons.push_back("\xef\x84\xb8 Chevron Circle Right");
    m_icons.push_back("\xef\x84\xb9 Chevron Circle Up");
    m_icons.push_back("\xef\x81\xb8 Chevron Down");
    m_icons.push_back("\xef\x81\x93 Chevron Left");
    m_icons.push_back("\xef\x81\x94 Chevron Right");
    m_icons.push_back("\xef\x81\xb7 Chevron Up");
    m_icons.push_back("\xef\x86\xae Child");
    m_icons.push_back("\xef\x94\x9d Church");
    m_icons.push_back("\xef\x84\x91 Circle");
    m_icons.push_back("\xef\x87\x8e Circle Notch");
    m_icons.push_back("\xef\x99\x8f City");
    m_icons.push_back("\xef\x9f\xb2 Clinic Medical");
    m_icons.push_back("\xef\x8c\xa8 Clipboard");
    m_icons.push_back("\xef\x91\xac Clipboard Check");
    m_icons.push_back("\xef\x91\xad Clipboard List");
    m_icons.push_back("\xef\x80\x97 Clock");
    m_icons.push_back("\xef\x89\x8d Clone");
    m_icons.push_back("\xef\x88\x8a Closed Captioning");
    m_icons.push_back("\xef\x83\x82 Cloud");
    m_icons.push_back("\xef\x8e\x81 Cloud Download Alt");
    m_icons.push_back("\xef\x9c\xbb Cloud Meatball");
    m_icons.push_back("\xef\x9b\x83 Cloud Moon");
    m_icons.push_back("\xef\x9c\xbc Cloud Moon Rain");
    m_icons.push_back("\xef\x9c\xbd Cloud Rain");
    m_icons.push_back("\xef\x9d\x80 Cloud Showers Heavy");
    m_icons.push_back("\xef\x9b\x84 Cloud Sun");
    m_icons.push_back("\xef\x9d\x83 Cloud Sun Rain");
    m_icons.push_back("\xef\x8e\x82 Cloud Upload Alt");
    m_icons.push_back("\xef\x95\xa1 Cocktail");
    m_icons.push_back("\xef\x84\xa1 Code");
    m_icons.push_back("\xef\x84\xa6 Code Branch");
    m_icons.push_back("\xef\x83\xb4 Coffee");
    m_icons.push_back("\xef\x80\x93 Cog");
    m_icons.push_back("\xef\x82\x85 Cogs");
    m_icons.push_back("\xef\x94\x9e Coins");
    m_icons.push_back("\xef\x83\x9b Columns");
    m_icons.push_back("\xef\x81\xb5 Comment");
    m_icons.push_back("\xef\x89\xba Comment Alt");
    m_icons.push_back("\xef\x99\x91 Comment Dollar");
    m_icons.push_back("\xef\x92\xad Comment Dots");
    m_icons.push_back("\xef\x9f\xb5 Comment Medical");
    m_icons.push_back("\xef\x92\xb3 Comment Slash");
    m_icons.push_back("\xef\x82\x86 Comments");
    m_icons.push_back("\xef\x99\x93 Comments Dollar");
    m_icons.push_back("\xef\x94\x9f Compact Disc");
    m_icons.push_back("\xef\x85\x8e Compass");
    m_icons.push_back("\xef\x81\xa6 Compress");
    m_icons.push_back("\xef\x90\xa2 Compress Alt");
    m_icons.push_back("\xef\x9e\x8c Compress Arrows Alt");
    m_icons.push_back("\xef\x95\xa2 Concierge Bell");
    m_icons.push_back("\xef\x95\xa3 Cookie");
    m_icons.push_back("\xef\x95\xa4 Cookie Bite");
    m_icons.push_back("\xef\x83\x85 Copy");
    m_icons.push_back("\xef\x87\xb9 Copyright");
    m_icons.push_back("\xef\x92\xb8 Couch");
    m_icons.push_back("\xef\x82\x9d Credit Card");
    m_icons.push_back("\xef\x84\xa5 Crop");
    m_icons.push_back("\xef\x95\xa5 Crop Alt");
    m_icons.push_back("\xef\x99\x94 Cross");
    m_icons.push_back("\xef\x81\x9b Crosshairs");
    m_icons.push_back("\xef\x94\xa0 Crow");
    m_icons.push_back("\xef\x94\xa1 Crown");
    m_icons.push_back("\xef\x9f\xb7 Crutch");
    m_icons.push_back("\xef\x86\xb2 Cube");
    m_icons.push_back("\xef\x86\xb3 Cubes");
    m_icons.push_back("\xef\x83\x84 Cut");
    m_icons.push_back("\xef\x87\x80 Database");
    m_icons.push_back("\xef\x8a\xa4 Deaf");
    m_icons.push_back("\xef\x9d\x87 Democrat");
    m_icons.push_back("\xef\x84\x88 Desktop");
    m_icons.push_back("\xef\x99\x95 Dharmachakra");
    m_icons.push_back("\xef\x91\xb0 Diagnoses");
    m_icons.push_back("\xef\x94\xa2 Dice");
    m_icons.push_back("\xef\x9b\x8f Dice D20");
    m_icons.push_back("\xef\x9b\x91 Dice D6");
    m_icons.push_back("\xef\x94\xa3 Dice Five");
    m_icons.push_back("\xef\x94\xa4 Dice Four");
    m_icons.push_back("\xef\x94\xa5 Dice One");
    m_icons.push_back("\xef\x94\xa6 Dice Six");
    m_icons.push_back("\xef\x94\xa7 Dice Three");
    m_icons.push_back("\xef\x94\xa8 Dice Two");
    m_icons.push_back("\xef\x95\xa6 Digital Tachograph");
    m_icons.push_back("\xef\x97\xab Directions");
    m_icons.push_back("\xef\x9f\xba Disease");
    m_icons.push_back("\xef\x94\xa9 Divide");
    m_icons.push_back("\xef\x95\xa7 Dizzy");
    m_icons.push_back("\xef\x91\xb1 Dna");
    m_icons.push_back("\xef\x9b\x93 Dog");
    m_icons.push_back("\xef\x85\x95 Dollar Sign");
    m_icons.push_back("\xef\x91\xb2 Dolly");
    m_icons.push_back("\xef\x91\xb4 Dolly Flatbed");
    m_icons.push_back("\xef\x92\xb9 Donate");
    m_icons.push_back("\xef\x94\xaa Door Closed");
    m_icons.push_back("\xef\x94\xab Door Open");
    m_icons.push_back("\xef\x86\x92 Dot Circle");
    m_icons.push_back("\xef\x92\xba Dove");
    m_icons.push_back("\xef\x80\x99 Download");
    m_icons.push_back("\xef\x95\xa8 Drafting Compass");
    m_icons.push_back("\xef\x9b\x95 Dragon");
    m_icons.push_back("\xef\x97\xae Draw Polygon");
    m_icons.push_back("\xef\x95\xa9 Drum");
    m_icons.push_back("\xef\x95\xaa Drum Steelpan");
    m_icons.push_back("\xef\x9b\x97 Drumstick Bite");
    m_icons.push_back("\xef\x91\x8b Dumbbell");
    m_icons.push_back("\xef\x9e\x93 Dumpster");
    m_icons.push_back("\xef\x9e\x94 Dumpster Fire");
    m_icons.push_back("\xef\x9b\x99 Dungeon");
    m_icons.push_back("\xef\x81\x84 Edit");
    m_icons.push_back("\xef\x9f\xbb Egg");
    m_icons.push_back("\xef\x81\x92 Eject");
    m_icons.push_back("\xef\x85\x81 Ellipsis H");
    m_icons.push_back("\xef\x85\x82 Ellipsis V");
    m_icons.push_back("\xef\x83\xa0 Envelope");
    m_icons.push_back("\xef\x8a\xb6 Envelope Open");
    m_icons.push_back("\xef\x99\x98 Envelope Open Text");
    m_icons.push_back("\xef\x86\x99 Envelope Square");
    m_icons.push_back("\xef\x94\xac Equals");
    m_icons.push_back("\xef\x84\xad Eraser");
    m_icons.push_back("\xef\x9e\x96 Ethernet");
    m_icons.push_back("\xef\x85\x93 Euro Sign");
    m_icons.push_back("\xef\x8d\xa2 Exchange Alt");
    m_icons.push_back("\xef\x84\xaa Exclamation");
    m_icons.push_back("\xef\x81\xaa Exclamation Circle");
    m_icons.push_back("\xef\x81\xb1 Exclamation Triangle");
    m_icons.push_back("\xef\x81\xa5 Expand");
    m_icons.push_back("\xef\x90\xa4 Expand Alt");
    m_icons.push_back("\xef\x8c\x9e Expand Arrows Alt");
    m_icons.push_back("\xef\x8d\x9d External Link Alt");
    m_icons.push_back("\xef\x8d\xa0 External Link Square Alt");
    m_icons.push_back("\xef\x81\xae Eye");
    m_icons.push_back("\xef\x87\xbb Eye Dropper");
    m_icons.push_back("\xef\x81\xb0 Eye Slash");
    m_icons.push_back("\xef\xa1\xa3 Fan");
    m_icons.push_back("\xef\x81\x89 Fast Backward");
    m_icons.push_back("\xef\x81\x90 Fast Forward");
    m_icons.push_back("\xee\x80\x85 Faucet");
    m_icons.push_back("\xef\x86\xac Fax");
    m_icons.push_back("\xef\x94\xad Feather");
    m_icons.push_back("\xef\x95\xab Feather Alt");
    m_icons.push_back("\xef\x86\x82 Female");
    m_icons.push_back("\xef\x83\xbb Fighter Jet");
    m_icons.push_back("\xef\x85\x9b File");
    m_icons.push_back("\xef\x85\x9c File Alt");
    m_icons.push_back("\xef\x87\x86 File Archive");
    m_icons.push_back("\xef\x87\x87 File Audio");
    m_icons.push_back("\xef\x87\x89 File Code");
    m_icons.push_back("\xef\x95\xac File Contract");
    m_icons.push_back("\xef\x9b\x9d File Csv");
    m_icons.push_back("\xef\x95\xad File Download");
    m_icons.push_back("\xef\x87\x83 File Excel");
    m_icons.push_back("\xef\x95\xae File Export");
    m_icons.push_back("\xef\x87\x85 File Image");
    m_icons.push_back("\xef\x95\xaf File Import");
    m_icons.push_back("\xef\x95\xb0 File Invoice");
    m_icons.push_back("\xef\x95\xb1 File Invoice Dollar");
    m_icons.push_back("\xef\x91\xb7 File Medical");
    m_icons.push_back("\xef\x91\xb8 File Medical Alt");
    m_icons.push_back("\xef\x87\x81 File Pdf");
    m_icons.push_back("\xef\x87\x84 File Powerpoint");
    m_icons.push_back("\xef\x95\xb2 File Prescription");
    m_icons.push_back("\xef\x95\xb3 File Signature");
    m_icons.push_back("\xef\x95\xb4 File Upload");
    m_icons.push_back("\xef\x87\x88 File Video");
    m_icons.push_back("\xef\x87\x82 File Word");
    m_icons.push_back("\xef\x95\xb5 Fill");
    m_icons.push_back("\xef\x95\xb6 Fill Drip");
    m_icons.push_back("\xef\x80\x88 Film");
    m_icons.push_back("\xef\x82\xb0 Filter");
    m_icons.push_back("\xef\x95\xb7 Fingerprint");
    m_icons.push_back("\xef\x81\xad Fire");
    m_icons.push_back("\xef\x9f\xa4 Fire Alt");
    m_icons.push_back("\xef\x84\xb4 Fire Extinguisher");
    m_icons.push_back("\xef\x91\xb9 First Aid");
    m_icons.push_back("\xef\x95\xb8 Fish");
    m_icons.push_back("\xef\x9b\x9e Fist Raised");
    m_icons.push_back("\xef\x80\xa4 Flag");
    m_icons.push_back("\xef\x84\x9e Flag Checkered");
    m_icons.push_back("\xef\x9d\x8d Flag Usa");
    m_icons.push_back("\xef\x83\x83 Flask");
    m_icons.push_back("\xef\x95\xb9 Flushed");
    m_icons.push_back("\xef\x81\xbb Folder");
    m_icons.push_back("\xef\x99\x9d Folder Minus");
    m_icons.push_back("\xef\x81\xbc Folder Open");
    m_icons.push_back("\xef\x99\x9e Folder Plus");
    m_icons.push_back("\xef\x80\xb1 Font");
    m_icons.push_back("\xef\x93\xa6 Font Awesome Logo Full");
    m_icons.push_back("\xef\x91\x8e Football Ball");
    m_icons.push_back("\xef\x81\x8e Forward");
    m_icons.push_back("\xef\x94\xae Frog");
    m_icons.push_back("\xef\x84\x99 Frown");
    m_icons.push_back("\xef\x95\xba Frown Open");
    m_icons.push_back("\xef\x99\xa2 Funnel Dollar");
    m_icons.push_back("\xef\x87\xa3 Futbol");
    m_icons.push_back("\xef\x84\x9b Gamepad");
    m_icons.push_back("\xef\x94\xaf Gas Pump");
    m_icons.push_back("\xef\x83\xa3 Gavel");
    m_icons.push_back("\xef\x8e\xa5 Gem");
    m_icons.push_back("\xef\x88\xad Genderless");
    m_icons.push_back("\xef\x9b\xa2 Ghost");
    m_icons.push_back("\xef\x81\xab Gift");
    m_icons.push_back("\xef\x9e\x9c Gifts");
    m_icons.push_back("\xef\x9e\x9f Glass Cheers");
    m_icons.push_back("\xef\x80\x80 Glass Martini");
    m_icons.push_back("\xef\x95\xbb Glass Martini Alt");
    m_icons.push_back("\xef\x9e\xa0 Glass Whiskey");
    m_icons.push_back("\xef\x94\xb0 Glasses");
    m_icons.push_back("\xef\x82\xac Globe");
    m_icons.push_back("\xef\x95\xbc Globe Africa");
    m_icons.push_back("\xef\x95\xbd Globe Americas");
    m_icons.push_back("\xef\x95\xbe Globe Asia");
    m_icons.push_back("\xef\x9e\xa2 Globe Europe");
    m_icons.push_back("\xef\x91\x90 Golf Ball");
    m_icons.push_back("\xef\x99\xa4 Gopuram");
    m_icons.push_back("\xef\x86\x9d Graduation Cap");
    m_icons.push_back("\xef\x94\xb1 Greater Than");
    m_icons.push_back("\xef\x94\xb2 Greater Than Equal");
    m_icons.push_back("\xef\x95\xbf Grimace");
    m_icons.push_back("\xef\x96\x80 Grin");
    m_icons.push_back("\xef\x96\x81 Grin Alt");
    m_icons.push_back("\xef\x96\x82 Grin Beam");
    m_icons.push_back("\xef\x96\x83 Grin Beam Sweat");
    m_icons.push_back("\xef\x96\x84 Grin Hearts");
    m_icons.push_back("\xef\x96\x85 Grin Squint");
    m_icons.push_back("\xef\x96\x86 Grin Squint Tears");
    m_icons.push_back("\xef\x96\x87 Grin Stars");
    m_icons.push_back("\xef\x96\x88 Grin Tears");
    m_icons.push_back("\xef\x96\x89 Grin Tongue");
    m_icons.push_back("\xef\x96\x8a Grin Tongue Squint");
    m_icons.push_back("\xef\x96\x8b Grin Tongue Wink");
    m_icons.push_back("\xef\x96\x8c Grin Wink");
    m_icons.push_back("\xef\x96\x8d Grip Horizontal");
    m_icons.push_back("\xef\x9e\xa4 Grip Lines");
    m_icons.push_back("\xef\x9e\xa5 Grip Lines Vertical");
    m_icons.push_back("\xef\x96\x8e Grip Vertical");
    m_icons.push_back("\xef\x9e\xa6 Guitar");
    m_icons.push_back("\xef\x83\xbd H Square");
    m_icons.push_back("\xef\xa0\x85 Hamburger");
    m_icons.push_back("\xef\x9b\xa3 Hammer");
    m_icons.push_back("\xef\x99\xa5 Hamsa");
    m_icons.push_back("\xef\x92\xbd Hand Holding");
    m_icons.push_back("\xef\x92\xbe Hand Holding Heart");
    m_icons.push_back("\xee\x81\x9c Hand Holding Medical");
    m_icons.push_back("\xef\x93\x80 Hand Holding Usd");
    m_icons.push_back("\xef\x93\x81 Hand Holding Water");
    m_icons.push_back("\xef\x89\x98 Hand Lizard");
    m_icons.push_back("\xef\xa0\x86 Hand Middle Finger");
    m_icons.push_back("\xef\x89\x96 Hand Paper");
    m_icons.push_back("\xef\x89\x9b Hand Peace");
    m_icons.push_back("\xef\x82\xa7 Hand Point Down");
    m_icons.push_back("\xef\x82\xa5 Hand Point Left");
    m_icons.push_back("\xef\x82\xa4 Hand Point Right");
    m_icons.push_back("\xef\x82\xa6 Hand Point Up");
    m_icons.push_back("\xef\x89\x9a Hand Pointer");
    m_icons.push_back("\xef\x89\x95 Hand Rock");
    m_icons.push_back("\xef\x89\x97 Hand Scissors");
    m_icons.push_back("\xee\x81\x9d Hand Sparkles");
    m_icons.push_back("\xef\x89\x99 Hand Spock");
    m_icons.push_back("\xef\x93\x82 Hands");
    m_icons.push_back("\xef\x93\x84 Hands Helping");
    m_icons.push_back("\xee\x81\x9e Hands Wash");
    m_icons.push_back("\xef\x8a\xb5 Handshake");
    m_icons.push_back("\xee\x81\x9f Handshake Alt Slash");
    m_icons.push_back("\xee\x81\xa0 Handshake Slash");
    m_icons.push_back("\xef\x9b\xa6 Hanukiah");
    m_icons.push_back("\xef\xa0\x87 Hard Hat");
    m_icons.push_back("\xef\x8a\x92 Hashtag");
    m_icons.push_back("\xef\xa3\x80 Hat Cowboy");
    m_icons.push_back("\xef\xa3\x81 Hat Cowboy Side");
    m_icons.push_back("\xef\x9b\xa8 Hat Wizard");
    m_icons.push_back("\xef\x82\xa0 Hdd");
    m_icons.push_back("\xee\x81\xa1 Head Side Cough");
    m_icons.push_back("\xee\x81\xa2 Head Side Cough Slash");
    m_icons.push_back("\xee\x81\xa3 Head Side Mask");
    m_icons.push_back("\xee\x81\xa4 Head Side Virus");
    m_icons.push_back("\xef\x87\x9c Heading");
    m_icons.push_back("\xef\x80\xa5 Headphones");
    m_icons.push_back("\xef\x96\x8f Headphones Alt");
    m_icons.push_back("\xef\x96\x90 Headset");
    m_icons.push_back("\xef\x80\x84 Heart");
    m_icons.push_back("\xef\x9e\xa9 Heart Broken");
    m_icons.push_back("\xef\x88\x9e Heartbeat");
    m_icons.push_back("\xef\x94\xb3 Helicopter");
    m_icons.push_back("\xef\x96\x91 Highlighter");
    m_icons.push_back("\xef\x9b\xac Hiking");
    m_icons.push_back("\xef\x9b\xad Hippo");
    m_icons.push_back("\xef\x87\x9a History");
    m_icons.push_back("\xef\x91\x93 Hockey Puck");
    m_icons.push_back("\xef\x9e\xaa Holly Berry");
    m_icons.push_back("\xef\x80\x95 Home");
    m_icons.push_back("\xef\x9b\xb0 Horse");
    m_icons.push_back("\xef\x9e\xab Horse Head");
    m_icons.push_back("\xef\x83\xb8 Hospital");
    m_icons.push_back("\xef\x91\xbd Hospital Alt");
    m_icons.push_back("\xef\x91\xbe Hospital Symbol");
    m_icons.push_back("\xef\xa0\x8d Hospital User");
    m_icons.push_back("\xef\x96\x93 Hot Tub");
    m_icons.push_back("\xef\xa0\x8f Hotdog");
    m_icons.push_back("\xef\x96\x94 Hotel");
    m_icons.push_back("\xef\x89\x94 Hourglass");
    m_icons.push_back("\xef\x89\x93 Hourglass End");
    m_icons.push_back("\xef\x89\x92 Hourglass Half");
    m_icons.push_back("\xef\x89\x91 Hourglass Start");
    m_icons.push_back("\xef\x9b\xb1 House Damage");
    m_icons.push_back("\xee\x81\xa5 House User");
    m_icons.push_back("\xef\x9b\xb2 Hryvnia");
    m_icons.push_back("\xef\x89\x86 I Cursor");
    m_icons.push_back("\xef\xa0\x90 Ice Cream");
    m_icons.push_back("\xef\x9e\xad Icicles");
    m_icons.push_back("\xef\xa1\xad Icons");
    m_icons.push_back("\xef\x8b\x81 Id Badge");
    m_icons.push_back("\xef\x8b\x82 Id Card");
    m_icons.push_back("\xef\x91\xbf Id Card Alt");
    m_icons.push_back("\xef\x9e\xae Igloo");
    m_icons.push_back("\xef\x80\xbe Image");
    m_icons.push_back("\xef\x8c\x82 Images");
    m_icons.push_back("\xef\x80\x9c Inbox");
    m_icons.push_back("\xef\x80\xbc Indent");
    m_icons.push_back("\xef\x89\xb5 Industry");
    m_icons.push_back("\xef\x94\xb4 Infinity");
    m_icons.push_back("\xef\x84\xa9 Info");
    m_icons.push_back("\xef\x81\x9a Info Circle");
    m_icons.push_back("\xef\x80\xb3 Italic");
    m_icons.push_back("\xef\x99\xa9 Jedi");
    m_icons.push_back("\xef\x96\x95 Joint");
    m_icons.push_back("\xef\x99\xaa Journal Whills");
    m_icons.push_back("\xef\x99\xab Kaaba");
    m_icons.push_back("\xef\x82\x84 Key");
    m_icons.push_back("\xef\x84\x9c Keyboard");
    m_icons.push_back("\xef\x99\xad Khanda");
    m_icons.push_back("\xef\x96\x96 Kiss");
    m_icons.push_back("\xef\x96\x97 Kiss Beam");
    m_icons.push_back("\xef\x96\x98 Kiss Wink Heart");
    m_icons.push_back("\xef\x94\xb5 Kiwi Bird");
    m_icons.push_back("\xef\x99\xaf Landmark");
    m_icons.push_back("\xef\x86\xab Language");
    m_icons.push_back("\xef\x84\x89 Laptop");
    m_icons.push_back("\xef\x97\xbc Laptop Code");
    m_icons.push_back("\xee\x81\xa6 Laptop House");
    m_icons.push_back("\xef\xa0\x92 Laptop Medical");
    m_icons.push_back("\xef\x96\x99 Laugh");
    m_icons.push_back("\xef\x96\x9a Laugh Beam");
    m_icons.push_back("\xef\x96\x9b Laugh Squint");
    m_icons.push_back("\xef\x96\x9c Laugh Wink");
    m_icons.push_back("\xef\x97\xbd Layer Group");
    m_icons.push_back("\xef\x81\xac Leaf");
    m_icons.push_back("\xef\x82\x94 Lemon");
    m_icons.push_back("\xef\x94\xb6 Less Than");
    m_icons.push_back("\xef\x94\xb7 Less Than Equal");
    m_icons.push_back("\xef\x8e\xbe Level Down Alt");
    m_icons.push_back("\xef\x8e\xbf Level Up Alt");
    m_icons.push_back("\xef\x87\x8d Life Ring");
    m_icons.push_back("\xef\x83\xab Lightbulb");
    m_icons.push_back("\xef\x83\x81 Link");
    m_icons.push_back("\xef\x86\x95 Lira Sign");
    m_icons.push_back("\xef\x80\xba List");
    m_icons.push_back("\xef\x80\xa2 List Alt");
    m_icons.push_back("\xef\x83\x8b List Ol");
    m_icons.push_back("\xef\x83\x8a List Ul");
    m_icons.push_back("\xef\x84\xa4 Location Arrow");
    m_icons.push_back("\xef\x80\xa3 Lock");
    m_icons.push_back("\xef\x8f\x81 Lock Open");
    m_icons.push_back("\xef\x8c\x89 Long Arrow Alt Down");
    m_icons.push_back("\xef\x8c\x8a Long Arrow Alt Left");
    m_icons.push_back("\xef\x8c\x8b Long Arrow Alt Right");
    m_icons.push_back("\xef\x8c\x8c Long Arrow Alt Up");
    m_icons.push_back("\xef\x8a\xa8 Low Vision");
    m_icons.push_back("\xef\x96\x9d Luggage Cart");
    m_icons.push_back("\xef\x98\x84 Lungs");
    m_icons.push_back("\xee\x81\xa7 Lungs Virus");
    m_icons.push_back("\xef\x83\x90 Magic");
    m_icons.push_back("\xef\x81\xb6 Magnet");
    m_icons.push_back("\xef\x99\xb4 Mail Bulk");
    m_icons.push_back("\xef\x86\x83 Male");
    m_icons.push_back("\xef\x89\xb9 Map");
    m_icons.push_back("\xef\x96\x9f Map Marked");
    m_icons.push_back("\xef\x96\xa0 Map Marked Alt");
    m_icons.push_back("\xef\x81\x81 Map Marker");
    m_icons.push_back("\xef\x8f\x85 Map Marker Alt");
    m_icons.push_back("\xef\x89\xb6 Map Pin");
    m_icons.push_back("\xef\x89\xb7 Map Signs");
    m_icons.push_back("\xef\x96\xa1 Marker");
    m_icons.push_back("\xef\x88\xa2 Mars");
    m_icons.push_back("\xef\x88\xa7 Mars Double");
    m_icons.push_back("\xef\x88\xa9 Mars Stroke");
    m_icons.push_back("\xef\x88\xab Mars Stroke H");
    m_icons.push_back("\xef\x88\xaa Mars Stroke V");
    m_icons.push_back("\xef\x9b\xba Mask");
    m_icons.push_back("\xef\x96\xa2 Medal");
    m_icons.push_back("\xef\x83\xba Medkit");
    m_icons.push_back("\xef\x84\x9a Meh");
    m_icons.push_back("\xef\x96\xa4 Meh Blank");
    m_icons.push_back("\xef\x96\xa5 Meh Rolling Eyes");
    m_icons.push_back("\xef\x94\xb8 Memory");
    m_icons.push_back("\xef\x99\xb6 Menorah");
    m_icons.push_back("\xef\x88\xa3 Mercury");
    m_icons.push_back("\xef\x9d\x93 Meteor");
    m_icons.push_back("\xef\x8b\x9b Microchip");
    m_icons.push_back("\xef\x84\xb0 Microphone");
    m_icons.push_back("\xef\x8f\x89 Microphone Alt");
    m_icons.push_back("\xef\x94\xb9 Microphone Alt Slash");
    m_icons.push_back("\xef\x84\xb1 Microphone Slash");
    m_icons.push_back("\xef\x98\x90 Microscope");
    m_icons.push_back("\xef\x81\xa8 Minus");
    m_icons.push_back("\xef\x81\x96 Minus Circle");
    m_icons.push_back("\xef\x85\x86 Minus Square");
    m_icons.push_back("\xef\x9e\xb5 Mitten");
    m_icons.push_back("\xef\x84\x8b Mobile");
    m_icons.push_back("\xef\x8f\x8d Mobile Alt");
    m_icons.push_back("\xef\x83\x96 Money Bill");
    m_icons.push_back("\xef\x8f\x91 Money Bill Alt");
    m_icons.push_back("\xef\x94\xba Money Bill Wave");
    m_icons.push_back("\xef\x94\xbb Money Bill Wave Alt");
    m_icons.push_back("\xef\x94\xbc Money Check");
    m_icons.push_back("\xef\x94\xbd Money Check Alt");
    m_icons.push_back("\xef\x96\xa6 Monument");
    m_icons.push_back("\xef\x86\x86 Moon");
    m_icons.push_back("\xef\x96\xa7 Mortar Pestle");
    m_icons.push_back("\xef\x99\xb8 Mosque");
    m_icons.push_back("\xef\x88\x9c Motorcycle");
    m_icons.push_back("\xef\x9b\xbc Mountain");
    m_icons.push_back("\xef\xa3\x8c Mouse");
    m_icons.push_back("\xef\x89\x85 Mouse Pointer");
    m_icons.push_back("\xef\x9e\xb6 Mug Hot");
    m_icons.push_back("\xef\x80\x81 Music");
    m_icons.push_back("\xef\x9b\xbf Network Wired");
    m_icons.push_back("\xef\x88\xac Neuter");
    m_icons.push_back("\xef\x87\xaa Newspaper");
    m_icons.push_back("\xef\x94\xbe Not Equal");
    m_icons.push_back("\xef\x92\x81 Notes Medical");
    m_icons.push_back("\xef\x89\x87 Object Group");
    m_icons.push_back("\xef\x89\x88 Object Ungroup");
    m_icons.push_back("\xef\x98\x93 Oil Can");
    m_icons.push_back("\xef\x99\xb9 Om");
    m_icons.push_back("\xef\x9c\x80 Otter");
    m_icons.push_back("\xef\x80\xbb Outdent");
    m_icons.push_back("\xef\xa0\x95 Pager");
    m_icons.push_back("\xef\x87\xbc Paint Brush");
    m_icons.push_back("\xef\x96\xaa Paint Roller");
    m_icons.push_back("\xef\x94\xbf Palette");
    m_icons.push_back("\xef\x92\x82 Pallet");
    m_icons.push_back("\xef\x87\x98 Paper Plane");
    m_icons.push_back("\xef\x83\x86 Paperclip");
    m_icons.push_back("\xef\x93\x8d Parachute Box");
    m_icons.push_back("\xef\x87\x9d Paragraph");
    m_icons.push_back("\xef\x95\x80 Parking");
    m_icons.push_back("\xef\x96\xab Passport");
    m_icons.push_back("\xef\x99\xbb Pastafarianism");
    m_icons.push_back("\xef\x83\xaa Paste");
    m_icons.push_back("\xef\x81\x8c Pause");
    m_icons.push_back("\xef\x8a\x8b Pause Circle");
    m_icons.push_back("\xef\x86\xb0 Paw");
    m_icons.push_back("\xef\x99\xbc Peace");
    m_icons.push_back("\xef\x8c\x84 Pen");
    m_icons.push_back("\xef\x8c\x85 Pen Alt");
    m_icons.push_back("\xef\x96\xac Pen Fancy");
    m_icons.push_back("\xef\x96\xad Pen Nib");
    m_icons.push_back("\xef\x85\x8b Pen Square");
    m_icons.push_back("\xef\x8c\x83 Pencil Alt");
    m_icons.push_back("\xef\x96\xae Pencil Ruler");
    m_icons.push_back("\xee\x81\xa8 People Arrows");
    m_icons.push_back("\xef\x93\x8e People Carry");
    m_icons.push_back("\xef\xa0\x96 Pepper Hot");
    m_icons.push_back("\xef\x8a\x95 Percent");
    m_icons.push_back("\xef\x95\x81 Percentage");
    m_icons.push_back("\xef\x9d\x96 Person Booth");
    m_icons.push_back("\xef\x82\x95 Phone");
    m_icons.push_back("\xef\xa1\xb9 Phone Alt");
    m_icons.push_back("\xef\x8f\x9d Phone Slash");
    m_icons.push_back("\xef\x82\x98 Phone Square");
    m_icons.push_back("\xef\xa1\xbb Phone Square Alt");
    m_icons.push_back("\xef\x8a\xa0 Phone Volume");
    m_icons.push_back("\xef\xa1\xbc Photo Video");
    m_icons.push_back("\xef\x93\x93 Piggy Bank");
    m_icons.push_back("\xef\x92\x84 Pills");
    m_icons.push_back("\xef\xa0\x98 Pizza Slice");
    m_icons.push_back("\xef\x99\xbf Place Of Worship");
    m_icons.push_back("\xef\x81\xb2 Plane");
    m_icons.push_back("\xef\x96\xaf Plane Arrival");
    m_icons.push_back("\xef\x96\xb0 Plane Departure");
    m_icons.push_back("\xee\x81\xa9 Plane Slash");
    m_icons.push_back("\xef\x81\x8b Play");
    m_icons.push_back("\xef\x85\x84 Play Circle");
    m_icons.push_back("\xef\x87\xa6 Plug");
    m_icons.push_back("\xef\x81\xa7 Plus");
    m_icons.push_back("\xef\x81\x95 Plus Circle");
    m_icons.push_back("\xef\x83\xbe Plus Square");
    m_icons.push_back("\xef\x8b\x8e Podcast");
    m_icons.push_back("\xef\x9a\x81 Poll");
    m_icons.push_back("\xef\x9a\x82 Poll H");
    m_icons.push_back("\xef\x8b\xbe Poo");
    m_icons.push_back("\xef\x9d\x9a Poo Storm");
    m_icons.push_back("\xef\x98\x99 Poop");
    m_icons.push_back("\xef\x8f\xa0 Portrait");
    m_icons.push_back("\xef\x85\x94 Pound Sign");
    m_icons.push_back("\xef\x80\x91 Power Off");
    m_icons.push_back("\xef\x9a\x83 Pray");
    m_icons.push_back("\xef\x9a\x84 Praying Hands");
    m_icons.push_back("\xef\x96\xb1 Prescription");
    m_icons.push_back("\xef\x92\x85 Prescription Bottle");
    m_icons.push_back("\xef\x92\x86 Prescription Bottle Alt");
    m_icons.push_back("\xef\x80\xaf Print");
    m_icons.push_back("\xef\x92\x87 Procedures");
    m_icons.push_back("\xef\x95\x82 Project Diagram");
    m_icons.push_back("\xee\x81\xaa Pump Medical");
    m_icons.push_back("\xee\x81\xab Pump Soap");
    m_icons.push_back("\xef\x84\xae Puzzle Piece");
    m_icons.push_back("\xef\x80\xa9 Qrcode");
    m_icons.push_back("\xef\x84\xa8 Question");
    m_icons.push_back("\xef\x81\x99 Question Circle");
    m_icons.push_back("\xef\x91\x98 Quidditch");
    m_icons.push_back("\xef\x84\x8d Quote Left");
    m_icons.push_back("\xef\x84\x8e Quote Right");
    m_icons.push_back("\xef\x9a\x87 Quran");
    m_icons.push_back("\xef\x9e\xb9 Radiation");
    m_icons.push_back("\xef\x9e\xba Radiation Alt");
    m_icons.push_back("\xef\x9d\x9b Rainbow");
    m_icons.push_back("\xef\x81\xb4 Random");
    m_icons.push_back("\xef\x95\x83 Receipt");
    m_icons.push_back("\xef\xa3\x99 Record Vinyl");
    m_icons.push_back("\xef\x86\xb8 Recycle");
    m_icons.push_back("\xef\x80\x9e Redo");
    m_icons.push_back("\xef\x8b\xb9 Redo Alt");
    m_icons.push_back("\xef\x89\x9d Registered");
    m_icons.push_back("\xef\xa1\xbd Remove Format");
    m_icons.push_back("\xef\x8f\xa5 Reply");
    m_icons.push_back("\xef\x84\xa2 Reply All");
    m_icons.push_back("\xef\x9d\x9e Republican");
    m_icons.push_back("\xef\x9e\xbd Restroom");
    m_icons.push_back("\xef\x81\xb9 Retweet");
    m_icons.push_back("\xef\x93\x96 Ribbon");
    m_icons.push_back("\xef\x9c\x8b Ring");
    m_icons.push_back("\xef\x80\x98 Road");
    m_icons.push_back("\xef\x95\x84 Robot");
    m_icons.push_back("\xef\x84\xb5 Rocket");
    m_icons.push_back("\xef\x93\x97 Route");
    m_icons.push_back("\xef\x82\x9e Rss");
    m_icons.push_back("\xef\x85\x83 Rss Square");
    m_icons.push_back("\xef\x85\x98 Ruble Sign");
    m_icons.push_back("\xef\x95\x85 Ruler");
    m_icons.push_back("\xef\x95\x86 Ruler Combined");
    m_icons.push_back("\xef\x95\x87 Ruler Horizontal");
    m_icons.push_back("\xef\x95\x88 Ruler Vertical");
    m_icons.push_back("\xef\x9c\x8c Running");
    m_icons.push_back("\xef\x85\x96 Rupee Sign");
    m_icons.push_back("\xef\x96\xb3 Sad Cry");
    m_icons.push_back("\xef\x96\xb4 Sad Tear");
    m_icons.push_back("\xef\x9e\xbf Satellite");
    m_icons.push_back("\xef\x9f\x80 Satellite Dish");
    m_icons.push_back("\xef\x83\x87 Save");
    m_icons.push_back("\xef\x95\x89 School");
    m_icons.push_back("\xef\x95\x8a Screwdriver");
    m_icons.push_back("\xef\x9c\x8e Scroll");
    m_icons.push_back("\xef\x9f\x82 Sd Card");
    m_icons.push_back("\xef\x80\x82 Search");
    m_icons.push_back("\xef\x9a\x88 Search Dollar");
    m_icons.push_back("\xef\x9a\x89 Search Location");
    m_icons.push_back("\xef\x80\x90 Search Minus");
    m_icons.push_back("\xef\x80\x8e Search Plus");
    m_icons.push_back("\xef\x93\x98 Seedling");
    m_icons.push_back("\xef\x88\xb3 Server");
    m_icons.push_back("\xef\x98\x9f Shapes");
    m_icons.push_back("\xef\x81\xa4 Share");
    m_icons.push_back("\xef\x87\xa0 Share Alt");
    m_icons.push_back("\xef\x87\xa1 Share Alt Square");
    m_icons.push_back("\xef\x85\x8d Share Square");
    m_icons.push_back("\xef\x88\x8b Shekel Sign");
    m_icons.push_back("\xef\x8f\xad Shield Alt");
    m_icons.push_back("\xee\x81\xac Shield Virus");
    m_icons.push_back("\xef\x88\x9a Ship");
    m_icons.push_back("\xef\x92\x8b Shipping Fast");
    m_icons.push_back("\xef\x95\x8b Shoe Prints");
    m_icons.push_back("\xef\x8a\x90 Shopping Bag");
    m_icons.push_back("\xef\x8a\x91 Shopping Basket");
    m_icons.push_back("\xef\x81\xba Shopping Cart");
    m_icons.push_back("\xef\x8b\x8c Shower");
    m_icons.push_back("\xef\x96\xb6 Shuttle Van");
    m_icons.push_back("\xef\x93\x99 Sign");
    m_icons.push_back("\xef\x8b\xb6 Sign In Alt");
    m_icons.push_back("\xef\x8a\xa7 Sign Language");
    m_icons.push_back("\xef\x8b\xb5 Sign Out Alt");
    m_icons.push_back("\xef\x80\x92 Signal");
    m_icons.push_back("\xef\x96\xb7 Signature");
    m_icons.push_back("\xef\x9f\x84 Sim Card");
    m_icons.push_back("\xee\x81\xad Sink");
    m_icons.push_back("\xef\x83\xa8 Sitemap");
    m_icons.push_back("\xef\x9f\x85 Skating");
    m_icons.push_back("\xef\x9f\x89 Skiing");
    m_icons.push_back("\xef\x9f\x8a Skiing Nordic");
    m_icons.push_back("\xef\x95\x8c Skull");
    m_icons.push_back("\xef\x9c\x94 Skull Crossbones");
    m_icons.push_back("\xef\x9c\x95 Slash");
    m_icons.push_back("\xef\x9f\x8c Sleigh");
    m_icons.push_back("\xef\x87\x9e Sliders H");
    m_icons.push_back("\xef\x84\x98 Smile");
    m_icons.push_back("\xef\x96\xb8 Smile Beam");
    m_icons.push_back("\xef\x93\x9a Smile Wink");
    m_icons.push_back("\xef\x9d\x9f Smog");
    m_icons.push_back("\xef\x92\x8d Smoking");
    m_icons.push_back("\xef\x95\x8d Smoking Ban");
    m_icons.push_back("\xef\x9f\x8d Sms");
    m_icons.push_back("\xef\x9f\x8e Snowboarding");
    m_icons.push_back("\xef\x8b\x9c Snowflake");
    m_icons.push_back("\xef\x9f\x90 Snowman");
    m_icons.push_back("\xef\x9f\x92 Snowplow");
    m_icons.push_back("\xee\x81\xae Soap");
    m_icons.push_back("\xef\x9a\x96 Socks");
    m_icons.push_back("\xef\x96\xba Solar Panel");
    m_icons.push_back("\xef\x83\x9c Sort");
    m_icons.push_back("\xef\x85\x9d Sort Alpha Down");
    m_icons.push_back("\xef\xa2\x81 Sort Alpha Down Alt");
    m_icons.push_back("\xef\x85\x9e Sort Alpha Up");
    m_icons.push_back("\xef\xa2\x82 Sort Alpha Up Alt");
    m_icons.push_back("\xef\x85\xa0 Sort Amount Down");
    m_icons.push_back("\xef\xa2\x84 Sort Amount Down Alt");
    m_icons.push_back("\xef\x85\xa1 Sort Amount Up");
    m_icons.push_back("\xef\xa2\x85 Sort Amount Up Alt");
    m_icons.push_back("\xef\x83\x9d Sort Down");
    m_icons.push_back("\xef\x85\xa2 Sort Numeric Down");
    m_icons.push_back("\xef\xa2\x86 Sort Numeric Down Alt");
    m_icons.push_back("\xef\x85\xa3 Sort Numeric Up");
    m_icons.push_back("\xef\xa2\x87 Sort Numeric Up Alt");
    m_icons.push_back("\xef\x83\x9e Sort Up");
    m_icons.push_back("\xef\x96\xbb Spa");
    m_icons.push_back("\xef\x86\x97 Space Shuttle");
    m_icons.push_back("\xef\xa2\x91 Spell Check");
    m_icons.push_back("\xef\x9c\x97 Spider");
    m_icons.push_back("\xef\x84\x90 Spinner");
    m_icons.push_back("\xef\x96\xbc Splotch");
    m_icons.push_back("\xef\x96\xbd Spray Can");
    m_icons.push_back("\xef\x83\x88 Square");
    m_icons.push_back("\xef\x91\x9c Square Full");
    m_icons.push_back("\xef\x9a\x98 Square Root Alt");
    m_icons.push_back("\xef\x96\xbf Stamp");
    m_icons.push_back("\xef\x80\x85 Star");
    m_icons.push_back("\xef\x9a\x99 Star And Crescent");
    m_icons.push_back("\xef\x82\x89 Star Half");
    m_icons.push_back("\xef\x97\x80 Star Half Alt");
    m_icons.push_back("\xef\x9a\x9a Star Of David");
    m_icons.push_back("\xef\x98\xa1 Star Of Life");
    m_icons.push_back("\xef\x81\x88 Step Backward");
    m_icons.push_back("\xef\x81\x91 Step Forward");
    m_icons.push_back("\xef\x83\xb1 Stethoscope");
    m_icons.push_back("\xef\x89\x89 Sticky Note");
    m_icons.push_back("\xef\x81\x8d Stop");
    m_icons.push_back("\xef\x8a\x8d Stop Circle");
    m_icons.push_back("\xef\x8b\xb2 Stopwatch");
    m_icons.push_back("\xee\x81\xaf Stopwatch 20");
    m_icons.push_back("\xef\x95\x8e Store");
    m_icons.push_back("\xef\x95\x8f Store Alt");
    m_icons.push_back("\xee\x81\xb0 Store Alt Slash");
    m_icons.push_back("\xee\x81\xb1 Store Slash");
    m_icons.push_back("\xef\x95\x90 Stream");
    m_icons.push_back("\xef\x88\x9d Street View");
    m_icons.push_back("\xef\x83\x8c Strikethrough");
    m_icons.push_back("\xef\x95\x91 Stroopwafel");
    m_icons.push_back("\xef\x84\xac Subscript");
    m_icons.push_back("\xef\x88\xb9 Subway");
    m_icons.push_back("\xef\x83\xb2 Suitcase");
    m_icons.push_back("\xef\x97\x81 Suitcase Rolling");
    m_icons.push_back("\xef\x86\x85 Sun");
    m_icons.push_back("\xef\x84\xab Superscript");
    m_icons.push_back("\xef\x97\x82 Surprise");
    m_icons.push_back("\xef\x97\x83 Swatchbook");
    m_icons.push_back("\xef\x97\x84 Swimmer");
    m_icons.push_back("\xef\x97\x85 Swimming Pool");
    m_icons.push_back("\xef\x9a\x9b Synagogue");
    m_icons.push_back("\xef\x80\xa1 Sync");
    m_icons.push_back("\xef\x8b\xb1 Sync Alt");
    m_icons.push_back("\xef\x92\x8e Syringe");
    m_icons.push_back("\xef\x83\x8e Table");
    m_icons.push_back("\xef\x91\x9d Table Tennis");
    m_icons.push_back("\xef\x84\x8a Tablet");
    m_icons.push_back("\xef\x8f\xba Tablet Alt");
    m_icons.push_back("\xef\x92\x90 Tablets");
    m_icons.push_back("\xef\x8f\xbd Tachometer Alt");
    m_icons.push_back("\xef\x80\xab Tag");
    m_icons.push_back("\xef\x80\xac Tags");
    m_icons.push_back("\xef\x93\x9b Tape");
    m_icons.push_back("\xef\x82\xae Tasks");
    m_icons.push_back("\xef\x86\xba Taxi");
    m_icons.push_back("\xef\x98\xae Teeth");
    m_icons.push_back("\xef\x98\xaf Teeth Open");
    m_icons.push_back("\xef\x9d\xa9 Temperature High");
    m_icons.push_back("\xef\x9d\xab Temperature Low");
    m_icons.push_back("\xef\x9f\x97 Tenge");
    m_icons.push_back("\xef\x84\xa0 Terminal");
    m_icons.push_back("\xef\x80\xb4 Text Height");
    m_icons.push_back("\xef\x80\xb5 Text Width");
    m_icons.push_back("\xef\x80\x8a Th");
    m_icons.push_back("\xef\x80\x89 Th Large");
    m_icons.push_back("\xef\x80\x8b Th List");
    m_icons.push_back("\xef\x98\xb0 Theater Masks");
    m_icons.push_back("\xef\x92\x91 Thermometer");
    m_icons.push_back("\xef\x8b\x8b Thermometer Empty");
    m_icons.push_back("\xef\x8b\x87 Thermometer Full");
    m_icons.push_back("\xef\x8b\x89 Thermometer Half");
    m_icons.push_back("\xef\x8b\x8a Thermometer Quarter");
    m_icons.push_back("\xef\x8b\x88 Thermometer Three Quarters");
    m_icons.push_back("\xef\x85\xa5 Thumbs Down");
    m_icons.push_back("\xef\x85\xa4 Thumbs Up");
    m_icons.push_back("\xef\x82\x8d Thumbtack");
    m_icons.push_back("\xef\x8f\xbf Ticket Alt");
    m_icons.push_back("\xef\x80\x8d Times");
    m_icons.push_back("\xef\x81\x97 Times Circle");
    m_icons.push_back("\xef\x81\x83 Tint");
    m_icons.push_back("\xef\x97\x87 Tint Slash");
    m_icons.push_back("\xef\x97\x88 Tired");
    m_icons.push_back("\xef\x88\x84 Toggle Off");
    m_icons.push_back("\xef\x88\x85 Toggle On");
    m_icons.push_back("\xef\x9f\x98 Toilet");
    m_icons.push_back("\xef\x9c\x9e Toilet Paper");
    m_icons.push_back("\xee\x81\xb2 Toilet Paper Slash");
    m_icons.push_back("\xef\x95\x92 Toolbox");
    m_icons.push_back("\xef\x9f\x99 Tools");
    m_icons.push_back("\xef\x97\x89 Tooth");
    m_icons.push_back("\xef\x9a\xa0 Torah");
    m_icons.push_back("\xef\x9a\xa1 Torii Gate");
    m_icons.push_back("\xef\x9c\xa2 Tractor");
    m_icons.push_back("\xef\x89\x9c Trademark");
    m_icons.push_back("\xef\x98\xb7 Traffic Light");
    m_icons.push_back("\xee\x81\x81 Trailer");
    m_icons.push_back("\xef\x88\xb8 Train");
    m_icons.push_back("\xef\x9f\x9a Tram");
    m_icons.push_back("\xef\x88\xa4 Transgender");
    m_icons.push_back("\xef\x88\xa5 Transgender Alt");
    m_icons.push_back("\xef\x87\xb8 Trash");
    m_icons.push_back("\xef\x8b\xad Trash Alt");
    m_icons.push_back("\xef\xa0\xa9 Trash Restore");
    m_icons.push_back("\xef\xa0\xaa Trash Restore Alt");
    m_icons.push_back("\xef\x86\xbb Tree");
    m_icons.push_back("\xef\x82\x91 Trophy");
    m_icons.push_back("\xef\x83\x91 Truck");
    m_icons.push_back("\xef\x93\x9e Truck Loading");
    m_icons.push_back("\xef\x98\xbb Truck Monster");
    m_icons.push_back("\xef\x93\x9f Truck Moving");
    m_icons.push_back("\xef\x98\xbc Truck Pickup");
    m_icons.push_back("\xef\x95\x93 Tshirt");
    m_icons.push_back("\xef\x87\xa4 Tty");
    m_icons.push_back("\xef\x89\xac Tv");
    m_icons.push_back("\xef\x83\xa9 Umbrella");
    m_icons.push_back("\xef\x97\x8a Umbrella Beach");
    m_icons.push_back("\xef\x83\x8d Underline");
    m_icons.push_back("\xef\x83\xa2 Undo");
    m_icons.push_back("\xef\x8b\xaa Undo Alt");
    m_icons.push_back("\xef\x8a\x9a Universal Access");
    m_icons.push_back("\xef\x86\x9c University");
    m_icons.push_back("\xef\x84\xa7 Unlink");
    m_icons.push_back("\xef\x82\x9c Unlock");
    m_icons.push_back("\xef\x84\xbe Unlock Alt");
    m_icons.push_back("\xef\x82\x93 Upload");
    m_icons.push_back("\xef\x80\x87 User");
    m_icons.push_back("\xef\x90\x86 User Alt");
    m_icons.push_back("\xef\x93\xba User Alt Slash");
    m_icons.push_back("\xef\x93\xbb User Astronaut");
    m_icons.push_back("\xef\x93\xbc User Check");
    m_icons.push_back("\xef\x8a\xbd User Circle");
    m_icons.push_back("\xef\x93\xbd User Clock");
    m_icons.push_back("\xef\x93\xbe User Cog");
    m_icons.push_back("\xef\x93\xbf User Edit");
    m_icons.push_back("\xef\x94\x80 User Friends");
    m_icons.push_back("\xef\x94\x81 User Graduate");
    m_icons.push_back("\xef\x9c\xa8 User Injured");
    m_icons.push_back("\xef\x94\x82 User Lock");
    m_icons.push_back("\xef\x83\xb0 User Md");
    m_icons.push_back("\xef\x94\x83 User Minus");
    m_icons.push_back("\xef\x94\x84 User Ninja");
    m_icons.push_back("\xef\xa0\xaf User Nurse");
    m_icons.push_back("\xef\x88\xb4 User Plus");
    m_icons.push_back("\xef\x88\x9b User Secret");
    m_icons.push_back("\xef\x94\x85 User Shield");
    m_icons.push_back("\xef\x94\x86 User Slash");
    m_icons.push_back("\xef\x94\x87 User Tag");
    m_icons.push_back("\xef\x94\x88 User Tie");
    m_icons.push_back("\xef\x88\xb5 User Times");
    m_icons.push_back("\xef\x83\x80 Users");
    m_icons.push_back("\xef\x94\x89 Users Cog");
    m_icons.push_back("\xee\x81\xb3 Users Slash");
    m_icons.push_back("\xef\x8b\xa5 Utensil Spoon");
    m_icons.push_back("\xef\x8b\xa7 Utensils");
    m_icons.push_back("\xef\x97\x8b Vector Square");
    m_icons.push_back("\xef\x88\xa1 Venus");
    m_icons.push_back("\xef\x88\xa6 Venus Double");
    m_icons.push_back("\xef\x88\xa8 Venus Mars");
    m_icons.push_back("\xee\x82\x85 Vest");
    m_icons.push_back("\xee\x82\x86 Vest Patches");
    m_icons.push_back("\xef\x92\x92 Vial");
    m_icons.push_back("\xef\x92\x93 Vials");
    m_icons.push_back("\xef\x80\xbd Video");
    m_icons.push_back("\xef\x93\xa2 Video Slash");
    m_icons.push_back("\xef\x9a\xa7 Vihara");
    m_icons.push_back("\xee\x81\xb4 Virus");
    m_icons.push_back("\xee\x81\xb5 Virus Slash");
    m_icons.push_back("\xee\x81\xb6 Viruses");
    m_icons.push_back("\xef\xa2\x97 Voicemail");
    m_icons.push_back("\xef\x91\x9f Volleyball Ball");
    m_icons.push_back("\xef\x80\xa7 Volume Down");
    m_icons.push_back("\xef\x9a\xa9 Volume Mute");
    m_icons.push_back("\xef\x80\xa6 Volume Off");
    m_icons.push_back("\xef\x80\xa8 Volume Up");
    m_icons.push_back("\xef\x9d\xb2 Vote Yea");
    m_icons.push_back("\xef\x9c\xa9 Vr Cardboard");
    m_icons.push_back("\xef\x95\x94 Walking");
    m_icons.push_back("\xef\x95\x95 Wallet");
    m_icons.push_back("\xef\x92\x94 Warehouse");
    m_icons.push_back("\xef\x9d\xb3 Water");
    m_icons.push_back("\xef\xa0\xbe Wave Square");
    m_icons.push_back("\xef\x92\x96 Weight");
    m_icons.push_back("\xef\x97\x8d Weight Hanging");
    m_icons.push_back("\xef\x86\x93 Wheelchair");
    m_icons.push_back("\xef\x87\xab Wifi");
    m_icons.push_back("\xef\x9c\xae Wind");
    m_icons.push_back("\xef\x90\x90 Window Close");
    m_icons.push_back("\xef\x8b\x90 Window Maximize");
    m_icons.push_back("\xef\x8b\x91 Window Minimize");
    m_icons.push_back("\xef\x8b\x92 Window Restore");
    m_icons.push_back("\xef\x9c\xaf Wine Bottle");
    m_icons.push_back("\xef\x93\xa3 Wine Glass");
    m_icons.push_back("\xef\x97\x8e Wine Glass Alt");
    m_icons.push_back("\xef\x85\x99 Won Sign");
    m_icons.push_back("\xef\x82\xad Wrench");
    m_icons.push_back("\xef\x92\x97 X Ray");
    m_icons.push_back("\xef\x85\x97 Yen Sign");
    m_icons.push_back("\xef\x9a\xad Yin Yang");
}

void AddonsIcons::DisplayContents() {
    ImGui::BeginChild("Icons");
    {

        if (refresh & 1) {
            FillIcons(icons);
            refresh++;
        }

        static ImGuiTextFilter filter;
        filter.Draw("Filter", ImGui::GetFontSize() * 25);
        ImGui::SameLine();
        HelpMarker("Use , for OR, - for NOT, filtering includes hidden columns");

        ImVector<const char*> filteredData;
        if (filter.IsActive()) {
            for (int i = 0; i < icons.Size; i++) {
                if (filter.PassFilter(icons[i])) {
                    filteredData.push_back(icons[i]);
                }
            }
        }
        else {
            filteredData = icons;
        }

        static ImVector<const char*> selections;

        if (ImGui::BeginTable("IconsTable", 10, iconTableFlags)) {           
            for (int n = 0; n < filteredData.Size; n++) {

                const char * currentItem = filteredData[n];
                const bool itemIsSelected = selections.contains(currentItem);
                ImGui::TableNextColumn();
                if (ImGui::Selectable(currentItem, itemIsSelected)) {
                    if (ImGui::GetIO().KeyCtrl) {
                        if (itemIsSelected) {
                            selections.find_erase_unsorted(currentItem);
                        }
                        else {
                            selections.push_back(currentItem);
                        }
                    }
                    else {
                        selections.clear();
                        selections.push_back(currentItem);
                    }
                }

                if (ImGui::BeginPopupContextItem()) {
                    selections.clear();
                    selections.push_back(currentItem);
                    printf("(%s)\n", selections[0] - 20);


                    char buf[32];
                    sprintf(buf, selections[0]);
                    ImGui::Text("");
                    ImGui::SetKeyboardFocusHere();

                    ImGui::InputText("###edit", buf, IM_ARRAYSIZE(buf), ImGuiInputTextFlags_AutoSelectAll |
                        ImGuiInputTextFlags_ReadOnly);
                    ImGui::EndPopup();
                }  
            } 
            ImGui::EndTable();
        }
    }
    ImGui::EndChild();
}